name: Challenges
version: 1.0.0
website: https://github.com/MarcelCoding/challenges
api-version: "1.15"

main: net.marcel.challenge.Challenges

commands:
  modules:
  timer:
  distance:
  invsee:
  gamemode:
  team:
